name: 'Terraform Approval Run'

on:
  workflow_dispatch:
    inputs:
      target_folder:
        description: "Select the folder to execute terraform:"
        required: true
        type: choice
        options:
          - 01-Terraform-Install-Tools
          - 02-Terraform-Commands/terraform-manifests
          - 03-Terraform-Language-Basics/terraform-manifests
          - 04-Terraform-MetaArgument-provider/terraform-manifests
          - 05-Terraform-Variables-Output-Values/terraform-manifests
          - 06-Terraform-MetaArgument-count
          - 07-Terraform-Datasources
          - 08-Terraform-MetaArgument-foreach
          - 09-GKE-Public-Standard-Cluster/p1-gke-public-cluster
          - 10-Kubernetes-Resources-yaml
          - 11-Kubernetes-Resources-Terraform
          - 12-GKE-Private-Standard-Cluster-Autoscaler
          - 13-GKE-Horizontal-Pod-Autoscaling
          - 14-GKE-Vertical-Pod-Autoscaling
          - 15-GKE-Private-Standard-Cluster-private-endpoint
          - 16-GKE-Private-Autopilot-cluster
          - 17-GKE-Storage-Persistent-Disks
          - 18-GKE-Storage-CloudSQL
          - 19-GKE-Cloud-Storage-FUSE-CSI
          - 20-GKE-Storage-Filestore
          - 21-GKE-Gateway-API
          - 22-Terraform-Modules
          - 23-GKE-Infra-Custom-Terraform-Modules
          - 24-GKE-Infra-DevOps-CloudBuild-GitHub
          - 25-GKE-Workloads-Custom-Terraform-Modules
          - 26-GKE-Workloads-DevOps-CloudBuild-GitHub
          - 27-GKE-App-Continuous-Integration
          - 28-GKE-App-Continuous-Delivery
      header:
        description: "Terraform Actions"
        required: false
        type: string
        default: "Select all the Terraform action to perform"
      plan:
        description: "Run terraform plan"
        required: false
        type: boolean
        default: true
      apply:
        description: "Run terraform apply"
        required: false
        type: boolean
        default: false
      destroy:
        description: "Run terraform destroy"
        required: false
        type: boolean
        default: false
      import:
        description: "Run terraform import"
        required: false
        type: boolean
        default: false
      resource:
        description: "Resource to import (format: <resource_type>.<resource_name>) <gcp_resource_id>"
        required: false
        type: string
        default: "resource_type.resource_name gcp_resource_id"

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan:
    name: 'Terraform'
    runs-on: ubuntu-latest
    # environment: production

    defaults:
      run:
        working-directory: ${{ inputs.target_folder }}
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform & GCP
        uses: ./.github/actions/setup-terraform
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          target_folder: ${{ inputs.target_folder }}
          plan: ${{ inputs.plan }}
          apply: ${{ inputs.apply }}
          destroy: ${{ inputs.destroy }}      

      - name: Terraform Plan Generation
        if: ${{ inputs.plan }}
        # run: terraform plan -input=false
        run: |
          if [ "${{ inputs.destroy }}" == "true" ]; then
            terraform plan -destroy -out=tfplan -input=false
          else
            terraform plan -out=tfplan -input=false
          fi
      - name: Upload Terraform Plan
        if: ${{ inputs.plan }}
        uses: actions/upload-artifact@v4
        with:
          name: tfplanfile
          path: ${{ inputs.target_folder }}
          retention-days: 1
      

  terraform-execute:
    name: 'Terraform Execute'
    runs-on: ubuntu-latest
    environment: production
    needs: [terraform-plan]
    if: ${{ inputs.apply || inputs.destroy || inputs.import }}

    defaults:
      run:
        working-directory: ${{ inputs.target_folder }}
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Terraform & GCP
        uses: ./.github/actions/setup-terraform
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          target_folder: ${{ inputs.target_folder }}
          plan: ${{ inputs.plan }}
          apply: ${{ inputs.apply }}
          destroy: ${{ inputs.destroy }}
          import: ${{ inputs.import }}
          # subfolder: ${{ inputs.subfolder }}

      - name: Download Terraform Plan
        if: ${{ inputs.apply || inputs.destroy || inputs.import }}
        uses: actions/download-artifact@v4
        with:
          name: tfplanfile
          path: ${{ inputs.target_folder }}

      - name: Terraform Apply
        if: ${{ inputs.apply }}
        run: terraform apply -auto-approve tfplan
      - name: Terraform Destroy
        if: ${{ inputs.destroy }}
        run: terraform destroy -auto-approve tfplan
      - name: Terraform Import
        if: ${{ inputs.import }}
        run: terraform import ${{ inputs.resource }}



      